#!/usr/bin/env python
# Copyright (C) 2017 Emanuel Goncalves

__author__ = 'emanuel'

rpathways = {
    'mitochondria': [
        'R_CSm',
        'R_ACONTm',
        'R_ICDHxm',
        'R_ICDHyrm',
        'R_AKGMALtm',
        'R_CO2tm',
        'R_AKGDm',
        'R_SUCOAS1m',
        'R_NDPK1',
        'R_SUCOASm',
        'R_SUCD1m',
        'R_FUMm',
        'R_MDHm',
        'R_ASPTAm',
        'R_ASPGLUm',
        'R_ASPTA',
        'R_MDH',
        'R_AKGMALtm',
        'R_r1109',
        'R_ABTArm'
    ],

    'glycolysis': [
        'R_HEX1',
        'R_PGI',
        'R_PFK',
        'R_FBP',
        'R_FBA',
        'R_GAPD',
        'R_TPI',
        'R_PGK',
        'R_PGM',
        'R_ENO',
        'R_PYK',
        'R_LDH_L',
        'R_L_LACt2r',
        'R_PYRt2m',
        'R_PDHm',
    ],

    'ppp': [
        'R_G6PDH2r',
        'R_PGL',
        'R_GNDc',
        'R_RPI',
        'R_PRPPS',
        'R_PPM',
        'R_RPE',
        'R_TKT1',
        'R_TKT2',
        'R_TALA'
    ],

    'heme': [
        'R_BILIRED',
        'R_CPPPGO',
        'R_FCLTm',
        'R_FE3R2e',
        'R_HMBS',
        'R_HOXG',
        'R_PPBNGS',
        'R_PPPGOm',
        'R_UPP3S',
        'R_UPPDC1',
        'R_BIDGLCURr',
        'R_5AOPtm',
        'R_PPPG9tm'
    ],

    'ppp': [
        'R_ABTD',
        'R_ARABR',
        'R_DGULND',
        'R_DRBK',
        'R_DRPA',
        'R_G6PDH1rer',
        'R_G6PDH2r',
        'R_G6PDH2rer',
        'R_GNDer',
        'R_GULN3D',
        'R_GULNDer',
        'R_GUR1PP',
        'R_PGL',
        'R_PGLer',
        'R_PPM',
        'R_PRPPS',
        'R_RBK',
        'R_RBK_D',
        'R_RPE',
        'R_RPI',
        'R_TALA',
        'R_TKT1',
        'R_TKT2',
        'R_UDPG1P',
        'R_UDPGNP',
        'R_XYLK',
        'R_XYLTD_Dr',
        'R_XYLUR',
        'R_r0249',
        'R_r0570',
        'R_r0784',
        'R_r0796',
        'R_RE0124C',
        'R_GLYPHEHYc',
        'R_GNDc'
    ]
}
